### ISSUE TITLE
[Request] Insert the code rather than symbol

### ISSUE THREAD

**Issue by mrsafalpiya** [GoldsteinE/compe-latex-symbols#1]
An option to insert the code rather than symbol would be really useful in my case of writing latex mathematical expressions inside markdown file.

Inserting symbol (current behavior):
![image](https://user-images.githubusercontent.com/66555275/118159673-0a13b300-b43d-11eb-9e57-ca07c2a0d514.png)

Inserting code
![image](https://user-images.githubusercontent.com/66555275/118159892-519a3f00-b43d-11eb-818e-7db9a8fb20ae.png)

**Comment by GoldsteinE** [comment]
Hi!

I'm not sure how to implement this without duplicating all completion items. Maybe switching "mode" based on `&filetype` would work?

Probably some sort of setting would also be needed.

**Comment by mrsafalpiya** [comment]
I created a pull request #2 which implements this feature

Please check it out
